name: release
on:
  push:
    branches:
      - "+([0-9])?(.{+([0-9]),x}).x"
      - main
      - next
      - next-major
      - beta
      - alpha
    tags-ignore:
      - "*"
permissions:
  contents: write
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      new_release_version: ${{ steps.semantic-release.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
      # - name: Login to docker.io registry
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          go install github.com/goreleaser/goreleaser@latest
          npm install -g conventional-changelog-conventionalcommits
      - id: semantic-release
        name: Semantic release + goreleaser
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}